In [2]:
import numpy as np
#from rich import print

In [11]:
a1 = np.array([1,90,8,7,5])
a2 = np.array([2.3,3.2,1.2,2.2,1.5])
print(a1)
print(a1.shape)
print(a1.ndim)
print(a1.dtype)
print(np.sort(a1))
print(np.mean(a2))
print(np.median(a1))
print(np.max(a1))

[ 1 90  8  7  5]
(5,)
1
int32
[ 1  5  7  8 90]
2.08
7.0
90


In [25]:
a1 = np.zeros(10)
print(a1)
a2 = np.ones(10) #initializer for 1
print(a2)
a3 = np.arange(0, 11) #setting up a range
print(a3)
a4 = np.arange(-1, -11, -1) #negative range list
print(a4)
a2[3] = 100 #assignment
print(a2)
print(a2[0:4]) #slicing
print(a2[3])
a5 = np.arange(0, 50, 2)
print(a5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
[  1.   1.   1. 100.   1.   1.   1.   1.   1.   1.]
[  1.   1.   1. 100.]
100.0
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [35]:
''' ARRAY CREATION'''
print(np.linspace(0,1,5))                      # np.linspace(): Create 5 evenly spaced values from 0 to 1
print(np.random.randint(0,9,(2,3)))
print(np.identity(3))                          # np.identity(): Another 3x3 identity matrix
print(np.random.rand(2, 3))                    # np.random.rand(): 2x3 array of uniform random values
print(np.random.randn(2, 3))                   # np.random.randn(): 2x3 array of normal random values
print(np.random.randint(0, 10, size=(2, 3)))   # np.random.randint(): 2x3 array of random integers from 0 to 9
print("Empty",np.empty((2, 3)))                        # np.empty(): Create 2x3 uninitialized array 
#The contents of the array will be whatever random values already existed in that memory space—so it may look like garbage values.
print(np.full((2, 3), 7))                      # np.full(): Create 2x3 array filled with 7

[0.   0.25 0.5  0.75 1.  ]
[[8 4 4]
 [3 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.30826896 0.41623581 0.92778734]
 [0.25876711 0.34345909 0.17028273]]
[[ 1.51713461e-01  5.71644492e-04  1.21400299e+00]
 [ 4.53684007e-01 -3.15497100e-01  6.65561827e-01]]
[[4 2 0]
 [3 5 0]]
Empty [[ 1.51713461e-01  5.71644492e-04  1.21400299e+00]
 [ 4.53684007e-01 -3.15497100e-01  6.65561827e-01]]
[[7 7 7]
 [7 7 7]]


In [62]:
from rich import print
a1 = np.array([[2,5,2,4],[5,7,8,9]])
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Logarithmic : ", np.log(a))
print("Addition is : ", np.add(a, b))
print("Substraction is " , np.subtract(a,b))
print(a1)
print(np.sum(a1))
print("Vertical Sum",np.sum(a1, axis=0))
print("Horizontal Sum",np.sum(a1, axis=1))
print("Minumum Vetically",np.min(a1, axis=0))
print("Minumum Horizontally",np.min(a1, axis=1))
print(a1>2) # anwers in boolean of true or false
print(a1[a1>2]) #printvalues grater than 2 in the array

Logarithmic :  [[0.         0.69314718]
 [1.09861229 1.38629436]]

Addition is :  [[ 6  8]
 [10 12]]

Substraction is  [[-4 -4]
 [-4 -4]]

[[2 5 2 4]
 [5 7 8 9]]

42

Vertical Sum [ 7 12 10 13]

Horizontal Sum [13 29]

Minumum Vetically [2 5 2 4]

Minumum Horizontally [2 5]

[[False  True False  True]
 [ True  True  True  True]]

[5 4 5 7 8 9]

In [71]:
''' 
Create a NumPy array with values from 10 to 50.
Extract elements greater than 30
Multiply the array by 2
Find mean and standard deviation of the array '''
a1 = np.arange(10, 51)
print(a1)
print(a1[a1>30])
print(a1*2)
print("Mean", np.mean(a1))
print("Standard Deviation", np.std(a1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

[ 20  22  24  26  28  30  32  34  36  38  40  42  44  46  48  50  52  54
  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88  90
  92  94  96  98 100]

Mean 30.0

Standard Deviation 11.832159566199232

In [92]:
'''Task: Create a 3x3 matrix with numbers from 1 to 9.
Reshape it to a 1D array
Access the middle row from the original matrix
Replace the last element of reshaped array with 100
'''
a = np.random.randint(1, 10, (3, 3))
print(a)
b = a.flatten()
print(b)
c = a.ravel()
print(c)
b [-1] = 100
print(b)
print("Printing the middle row", a[1])

[[6 9 8]
 [7 3 3]
 [5 8 5]]

[6 9 8 7 3 3 5 8 5]

[6 9 8 7 3 3 5 8 5]

[  6   9   8   7   3   3   5   8 100]

Printing the middle row [7 3 3]

In [108]:
'''3.arr = np.array([5, 12, 17, 23, 45, 50, 66])
Find all even numbers
Count how many numbers are greater than 20
Replace all values less than 20 with 0
'''
arr = np.array([5, 12, 17, 23, 45, 50, 66])
arr1 =  arr[arr % 2 ==0]
print(arr1)
print(np.sum(arr>20))
print(np.max(arr[arr>20]))
arr[arr < 20] = 0
print(arr)

[12 50 66]

4

66

[ 0  0  0 23 45 50 66]

In [125]:
'''Generate a 5x5 matrix with random integers between 1 and 100.
Find the maximum and minimum value in the matrix
Find the sum of each row
Replace all values greater than 50 with -1
'''
a = np.random.randint(1, 101, (5,5,))
print(a)
print("MAX",np.max(a))
print("MIN",np.min(a))
print("Vertical min", np.min(a, axis = 0))
print("Vertical max", np.max(a, axis = 0))
print("Total SUM",np.sum(a))
print("Printing the sum of each row : ")
print(np.sum(a, axis = 1))
a[a>50] = -1
print("Replacing all the values which are >50 with -1\n",a)

[[64 14 72 69 58]
 [10  8 57 99 56]
 [33 36 13 79 44]
 [10 86 54 96 40]
 [71 41 26 96 85]]

MAX 99

MIN 8

Vertical min [10  8 13 69 40]

Vertical max [71 86 72 99 85]

Total SUM 1317

Printing the sum of each row :

[277 230 205 286 319]

Replacing all the values which are >50 with -1
 [[-1 14 -1 -1 -1]
 [10  8 -1 -1 -1]
 [33 36 13 -1 44]
 [10 -1 -1 -1 40]
 [-1 41 26 -1 -1]]